BUILD/CONFIG: Fix PGI compiler error: routing both inline and noinline
openucx/ucx pull request #10235
Opened 2024-10-16 14:15 UTC by tvegas1

## What
Fix PGI compiler errors found during `build_pgi` step like:
```
2024-10-10T08:54:25.0639396Z "/__w/1/s/contrib/../test/gtest/ucs/test_algorithm.cc", line 51: error #1626: routine is both "inline" and "noinline"
2024-10-10T08:54:25.0640811Z   UCS_TEST_F(test_algorithm, crc16) {
```

2024-10-16 17:19 UTC, tvegas1 commented
Confirmed that the failure at `==== Build with PGI compiler ====
` step is not seen anymore

2024-10-16 17:33 UTC, yosefe approved these changes

2024-10-16 17:34 UTC, yosefe requested changes
maybe we need to fix the UCS_TEST_F macro that defines both inline and noninline routine?

2024-10-16 19:53 UTC, brminich commented on config/m4/compiler.m4
> +                                 [--diag_suppress 1626],
shall we also update the comment above?

2024-10-17 08:18 UTC, tvegas1 commented
> maybe we need to fix the UCS_TEST_F macro that defines both inline and noninline routine?

I think the problem is with the compiler so I would not touch the code (which is gtest lib afaiu). Apparently it assumes that defining function as `static` inside class implies `inline` keyword, so when adding `__attribute__((noinline))` it declares a conflict.

```c++
class fails {
    static int __attribute__((noinline)) test() { return 1; }
};

class works {
    static int __attribute__((noinline)) test();
};
int __attribute__((noinline)) works::test() { return 1; }
```


For reference, from `UCS_TEST_F(gtest_common, auto_ptr)`, we get:
```c++
class gtest_common_auto_ptr_Test : public gtest_common {
...
    static ::testing::TestInfo *__attribute__((noinline)) create_test_info()
    {
        return ::testing::internal::MakeAndRegisterTestInfo(

```

2024-10-17 08:21 UTC, tvegas1 commented on config/m4/compiler.m4
> +                                 [--diag_suppress 1626],
force pushed

2024-10-17 09:42 UTC, yosefe approved these changes

2024-10-18 08:10 UTC, merged