CI: Convert Python2 testing scripts to Python3
openucx/ucx pull request #10290
Opened 2024-11-11 15:52 UTC by Alexey-Rivkin

## What?
Convert Python2 testing scripts to Python3.

## Why?
We missed the Python2 EOL date a bit (Jan 1, 2020).

2024-11-12 16:07 UTC, dpressle requested changes

2024-11-12 16:07 UTC, dpressle commented on test/apps/test_fuzzy_match.py
Do we want to also fix the shebang to python3 and not be dependent on default python settings?

2024-11-17 12:55 UTC, dpressle requested changes

2024-11-17 12:55 UTC, dpressle commented on test/apps/test_ucx_tls.py
python3?

2024-11-17 14:45 UTC, Alexey-Rivkin commented on test/apps/test_ucx_tls.py
Sure, thanks!

2024-11-17 14:45 UTC, Alexey-Rivkin commented on test/apps/test_ucx_tls.py
> +        print("return code " + str(status))
Done

2024-11-26 08:49 UTC, dpressle approved these changes

2024-11-29 13:36 UTC, yosefe approved these changes

2024-11-29 20:52 UTC, merged

2024-11-29 20:53 UTC, yosefe commented
@Alexey-Rivkin can u pls port to v1.18.x?