UCP/PROTO: Consider RNDV_PERF_DIFF
openucx/ucx pull request #10401
Opened 2024-12-30 10:11 UTC by rakhmets

## What?
Applies `UCX_RNDV_PERF_DIFF` setting effect for protov2. 

Cherry-picked from https://github.com/openucx/ucx/pull/10292.

## Why?
This control effect was removed during introducing perf-factors logic. This PR brings it back.

That how it looks like with that patch:
![image](https://github.com/user-attachments/assets/19986951-09c1-47e2-8d32-205aa6ce0a95)

2024-12-30 15:42 UTC, rakhmets commented
Test failures should be fixed with https://github.com/openucx/ucx/pull/10397.

2025-01-03 13:30 UTC, iyastreb commented on test/gtest/ucp/test_ucp_proto.cc
> +UCS_TEST_F(test_proto_perf, apply_zero_bias) {
Just wondering if it makes sense to add a mock test with `RNDV_PERF_DIFF` and make an assertion on selected protocols

2025-01-06 10:05 UTC, iyastreb commented on src/ucp/rndv/proto_rndv.c
> +    ucp_proto_perf_apply_bias(perf, params->perf_bias);
It seems applying this bias leads to slightly different performance numbers and therefore breaks the mock test:
[log1](https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/93242/logs/1357), [log2](https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/93242/logs/1380), [log3](https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/93242/logs/1375)

Expected protocol:
`{8247,   **377094**,           "multi-frag copy-in"},`
Actual protocol:
`8247-**363935** multi-frag copy-in`

Could it be due to adding this bias? If so, we should update here the numbers in mock test as well

2025-01-06 10:07 UTC, iyastreb commented
> Test failures should be fixed with #10397.

In fact only [one](https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/93127/logs/1225) of the test failure can be fixed by that PR. The others are triggered by changed perf calculation logic I guess

2025-01-07 09:25 UTC, brminich commented on src/ucp/rndv/proto_rndv.c
> +    ucp_proto_perf_apply_bias(perf, params->perf_bias);
don't we need to apply it for RTS only? E.g. now it is applied for RTR as well making it more preferable than get_zcopy

2025-01-13 18:12 UTC, rakhmets commented on src/ucp/rndv/proto_rndv.c
> +    ucp_proto_perf_apply_bias(perf, params->perf_bias);
Yes, it is because of adding the bias. UCX selects rendezvous earlier with this changes.

2025-01-13 18:17 UTC, rakhmets commented on src/ucp/rndv/proto_rndv.c
> +    ucp_proto_perf_apply_bias(perf, params->perf_bias);
I thought it is done in this way according to this comment: https://github.com/openucx/ucx/pull/10292#issuecomment-2469830879.

`ucp_proto_rndv_ctrl_init_params_t::perf_bias` is controlled by `UCX_RNDV_PERF_DIFF` in RTS protocol, and `ucp_proto_rndv_ctrl_init_params_t::perf_bias` is set to zero in RTR protocol.

2025-01-13 18:21 UTC, rakhmets commented on test/gtest/ucp/test_ucp_proto.cc
> +UCS_TEST_F(test_proto_perf, apply_zero_bias) {
Do you mean remove this test, and add test case to `test_ucp_proto_mock_rcx`?

2025-01-14 06:59 UTC, iyastreb commented on test/gtest/ucp/test_ucp_proto.cc
> +UCS_TEST_F(test_proto_perf, apply_zero_bias) {
I don't insist on removing this test
But adding new test to `test_ucp_proto_mock_rcx` looks like superior alternative, because we test the entire chain

2025-01-14 12:56 UTC, iyastreb approved these changes
Thanks for addressing my comments
Please note that there is approved PR for mock refactoring, that will be merged soon. You might need to slightly adapt mock test code

2025-01-17 11:01 UTC, iyastreb approved these changes

2025-01-17 17:04 UTC, brminich approved these changes

2025-01-20 18:48 UTC, yosefe commented on src/ucp/proto/proto_perf.c
> +void ucp_proto_perf_apply_bias(ucp_proto_perf_t *perf, double bias)
IMO it would be better to make it more generic, i.e something like
`void ucp_proto_perf_apply_func(ucp_proto_perf_t *perf, ucs_linear_func_t func, const char *name)`
`ucp_proto_perf_apply_func(perf, ucs_linear_func_make(0.0, 1.0 - bias), "bias");`

2025-01-20 18:48 UTC, yosefe commented on src/ucp/proto/proto_perf.c
> +    ucp_proto_perf_factor_id_t fid;
minor: rename fid to factor_id to align with other code

2025-01-20 18:48 UTC, yosefe commented on src/ucp/proto/proto_perf.c
> +            seg->perf_factors[fid] =
maybe better use a local array for the new factors value rather than update in place since ucp_proto_perf_node_update_factors does not expect them in place (though it works)

2025-01-21 18:20 UTC, yosefe commented on src/ucp/proto/proto_perf.c
> +                                    perf_factor);
this block seems very similar to ucp_proto_perf_node_update_factors body, can we unite common code?

2025-01-21 18:43 UTC, yosefe approved these changes

2025-01-22 07:12 UTC, brminich requested changes

2025-01-22 07:12 UTC, brminich commented on src/ucp/proto/proto_perf.h
> + * @param [in] title        Title for performance node that would be created
`name`

2025-01-22 08:29 UTC, rakhmets commented on src/ucp/proto/proto_perf.h
> + * @param [in] title        Title for performance node that would be created
Fixed.

2025-01-22 09:30 UTC, yosefe submitted a review, later dismissed

2025-01-22 10:53 UTC, yosefe approved these changes

2025-01-22 11:53 UTC, brminich approved these changes

2025-01-23 14:49 UTC, merged

2026-01-05 06:03 UTC, mkre commented
Hi @rakhmets, this change is causing some significant performance regressions for our application, see #11091. Can you please have a look?