UCT/API:amend uct md mem query semantic and docs
openucx/ucx pull request #5276
Opened 2020-06-10 16:39 UTC by Akshay-Venkatesh

## What
 - user populates field_mask as discussed from previous reviews and not the other way
 - change documentation to reflect above and simplify wording

2020-06-10 17:43 UTC, brminich requested changes

2020-06-10 17:54 UTC, brminich approved these changes

2020-06-11 05:53 UTC, brminich commented
bot:pipe:retest

2020-06-11 14:40 UTC, bureddy approved these changes

2020-06-11 14:43 UTC, yosefe approved these changes

2020-06-14 08:30 UTC, yosefe commented
bot:pipe:retest

2020-06-15 18:28 UTC, brminich commented
bot:pipe:retest

2020-06-29 14:21 UTC, shamisp commented on src/uct/api/uct.h
> +     * Index of the system device on which the buffer resides. E.g. NUMA/GPU
How one can obtain the index of the device ?

2026-07-02 13:36 UTC, gleon99 commented
Hi @Akshay-Venkatesh - we're cleaning up the UCX PR backlog and plan to close this PR in 7 days. Please let us know if you'd like to keep it open.

2026-07-19 13:21 UTC, closed without merging