Go Initial checkin
openucx/ucx pull request #5546
Opened 2020-08-07 21:53 UTC by bryanweingarten

This is the initial check-in for the Go bindings.

This includes initial code for 
* Context
* Context Params
* Worker
* Worker Params
* Endpoint
* Endpoint Params

2020-08-07 21:54 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2020-08-07 23:36 UTC, shamisp commented
@bryanweingarten  - very cool !!! 
Just do double check, do you have signed CLA for UCX project: https://www.openucx.org/license/

2020-08-08 09:13 UTC, yosefe commented
ok to test

2020-08-14 06:29 UTC, brminich commented
@bryanweingarten, can you please update commit messages according to https://github.com/openucx/ucx/wiki/Guidance-for-contributors#general-guidelines for CI to pass?

2020-08-14 07:59 UTC, brminich reviewed
👍 
can you please add simple hello world example to `./examples` and run it in CI in `./contrib/test_jenkins.sh`?

2020-08-14 07:59 UTC, brminich commented on bindings/go/pkg/ucp/context.go
> +	size_t length;
formatting is odd a bit. Is it done by go fmt?

2020-08-14 07:59 UTC, brminich commented on bindings/go/pkg/ucp/c.go
> +#cgo CFLAGS: -I/home/bryan/src/ucx/release/include
will you replace it with `pkg-config` eventually?

2020-08-14 07:59 UTC, brminich commented on bindings/go/pkg/ucp/context.go
> +    ucs_recursive_spinlock_t lock;
why do you need a lock per request?

2020-08-14 07:59 UTC, brminich commented on bindings/go/pkg/ucp/context_params.go
> +}
can also add `EnableAM` to request support for UCP Active Messages

2020-08-14 07:59 UTC, brminich commented on bindings/go/pkg/ucp/context.go
> +		ucs.LogErrorf("No such key %s, ignoring", status)
`"Unable to init config: %d", status` ?

2020-08-14 07:59 UTC, brminich commented on bindings/go/pkg/ucp/endpoint.go
> +/*
unused code

2020-08-14 07:59 UTC, brminich commented on bindings/go/pkg/ucp/endpoint_export.go
> +//export endpointErrorHandlerProxy
no need for this comment?

2020-08-14 07:59 UTC, brminich commented on bindings/go/pkg/ucs/log.go
> +#cgo CFLAGS: -I/home/bryan/src/ucx/release/include -DUCS_LOG_LEVEL_TRACE_LAST=UCS_LOG_LEVEL_LAST
need to avoid referring to specific path

2020-08-14 15:44 UTC, shamisp requested changes
Waiting for CLA.

2021-06-03 12:58 UTC, petro-rudenko commented
Please take a look to #6896

2026-07-02 13:36 UTC, gleon99 commented
Hi @bryanweingarten - we're cleaning up the UCX PR backlog and plan to close this PR in 7 days. Please let us know if you'd like to keep it open.

2026-07-19 13:21 UTC, closed without merging