[CI] fix command find grep for large count of files
openucx/ucx pull request #5820
Opened 2020-10-21 12:18 UTC by avildema

## What
CI: fix command find grep for large count of files

## Why ?
CI on Azure pipeline fail with 123 code on find grep

2020-10-21 12:29 UTC, hoopoepg commented on contrib/test_jenkins.sh
> +	missing=`find $srcdir -name \*.c -o -name \*.cc -exec grep -LP '\#\s*include\s+"config.h"' {} \;`
s/-LP/-LPH
to print file name

2020-10-21 12:44 UTC, hoopoepg approved these changes

2020-10-22 16:41 UTC, yosefe commented
bot:pipe:retest

2020-10-23 11:32 UTC, yosefe approved these changes

2020-10-23 11:38 UTC, yosefe requested changes
I tested this (added C file without include config.h) and it doesn't work

2020-10-23 12:35 UTC, hoopoepg approved these changes

2020-10-23 12:45 UTC, yosefe approved these changes
thanks, now it works
can you pls squash?

2020-10-25 09:23 UTC, merged