UCS/MEMORY: Add new type for host memory allocated by CUDA
openucx/ucx pull request #5878
Opened 2020-11-04 21:17 UTC by SeyedMir

## What
Add a new UCS memory type to distinguish between host memory that is allocated by CUDA and host memory that is not allocated by CUDA.

## Why ?
Host memory that is allocated by CUDA will be released by CUDA too. So, it is managed by CUDA and we need to distinguish it from host memory that is not managed by CUDA.

2020-11-04 21:19 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2020-11-04 21:23 UTC, dmitrygx requested changes

2020-11-04 21:23 UTC, dmitrygx commented on src/uct/cuda/base/cuda_md.c
> +        else if (is_managed) {
put on the same line with `}` from `if` block

2020-11-04 21:35 UTC, Akshay-Venkatesh commented
@SeyedMir You would also need to add CUDA_HOST to the list of memory types that cuda_copy transport can identify here https://github.com/openucx/ucx/blob/de000dab16c18249b9af2bbfecbd29321ec3ecee/src/uct/cuda/cuda_copy/cuda_copy_md.c#L37
I don't think that's been added.

2020-11-04 22:09 UTC, SeyedMir commented
@Akshay-Venkatesh Should I add CUDA_HOST to the list of memory types that cuda_copy transport can register too? I understand that CUDA_HOST is already registered, so I'm thinking we should not need that.

2020-11-04 22:42 UTC, shamisp commented
@SeyedMir  - Thanks for the patch. What is your affiliation ? thanks

2020-11-04 22:50 UTC, SeyedMir commented
@shamisp I'm with NVIDIA.

2020-11-05 08:31 UTC, yosefe commented
Do we need to distinguish CUDA_HOST from HOST just for memory release purpose?
how is it different than host memory allocated by malloc() vs. host memory allocated by mmap()?

2020-11-05 16:30 UTC, bureddy commented
Agree. we should not add need mem type unless we need to differentiate it from HOST memory in the protocols.
just adding to the list may also consume resources like mem_type_ep

2020-11-05 18:13 UTC, SeyedMir commented
@yosefe @bureddy Agreed. I had a use case in mind for which I thought we need to distinguish between CUDA_HOST and HOST memory types. It is not necessary.

2020-11-06 19:31 UTC, closed without merging