uct: fix cq creation failure using old ibv api
openucx/ucx pull request #5986
Opened 2020-12-04 08:02 UTC by dsharma283

With the rdma-core version 28.0 or higher the error code
returned by libibverbs for the case where ibv_cq_ex_to_cq
is not supported by the underlying transport has changed.
The transport layer now returns EOPNOTSUPP instead of 
ENOSYS.
Ucx is broken for all the transport devices which do not
have ibv_cq_ex_to_cq implemented. Fixing the error code
check in uct for IB devices.

Signed-off-by: Devesh Sharma <devesh.sharma@broadcom.com>

2020-12-04 08:04 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2020-12-04 08:09 UTC, brminich commented
ok to test

2020-12-04 08:12 UTC, brminich commented
@dsharma283, can you pleasse fix commit title according to https://github.com/openucx/ucx/wiki/Guidance-for-contributors#general-guidelines?
(seems need to use upper case for `UCT`)

2020-12-04 08:42 UTC, dsharma283 commented
> 
> 
> @dsharma283, can you pleasse fix commit title according to https://github.com/openucx/ucx/wiki/Guidance-for-contributors#general-guidelines?
> (seems need to use upper case for `UCT`)

Updated the patch subject line. Added one more change to make it backwards compatible.

2020-12-04 14:45 UTC, yosefe commented
/azp run

2020-12-04 14:47 UTC, yosefe commented
/azp run

2020-12-04 22:18 UTC, shamisp commented
@dsharma283 - Thanks for the patch ! Please add Broadcom copyright to the modified files. In order to merge the PR we need signed CLA: https://www.openucx.org/wp-content/uploads/2019/05/ucx-corporate-contributor-agrement.pdf  . Once it is signed, please send the copy to me. Thanks !

2020-12-04 22:19 UTC, shamisp requested changes
Pending - waiting for CLA

2020-12-05 11:10 UTC, yosefe commented
/azp run

2020-12-05 12:05 UTC, yosefe commented
/azp run

2020-12-05 15:23 UTC, dsharma283 commented
> @dsharma283 - Thanks for the patch ! Please add Broadcom copyright to the modified files. In order to merge the PR we need signed CLA: https://www.openucx.org/wp-content/uploads/2019/05/ucx-corporate-contributor-agrement.pdf . Once it is signed, please send the copy to me. Thanks !

Thanks Pasha for this note, let me take it to my Org and get back to you with approvals.

2020-12-17 14:57 UTC, dsharma283 commented
I am still taking time to come back on CLA. This may take some more time

2021-01-26 06:24 UTC, dsharma283 commented
@shamisp Hi, I have received a signed copy of CLA, Please let me know where I should send the Signed CLA. I will add the broadcom copyright to the modified files.

2021-01-26 15:19 UTC, shamisp commented
Please email to admin at ucfconsortium.org . Once it is sent, please let me know and I will make sure that it is counter signed.

2021-01-28 11:12 UTC, dsharma283 commented
@shamisp Sent!

2021-01-28 18:47 UTC, shamisp commented
The CLA was received.

2021-01-28 18:47 UTC, shamisp approved these changes

2021-01-28 18:48 UTC, shamisp commented
@yosefe FYI

2021-01-28 18:53 UTC, dmitrygx requested changes

2021-01-28 18:53 UTC, dmitrygx commented on src/uct/ib/base/ib_iface.c
> +    if (!cq && (errno == EOPNOTSUPP || errno == ENOSYS))
pls, warp each condition by `()`:
```
if (!cq && ((errno == EOPNOTSUPP) || (errno == ENOSYS)))
```

2021-01-28 22:02 UTC, shamisp commented
Please add Broadcom copyright to the header of the file.

2021-02-04 06:20 UTC, dsharma283 commented on src/uct/ib/base/ib_iface.c
> +    if (!cq && (errno == EOPNOTSUPP || errno == ENOSYS))
Done!

2021-02-04 14:40 UTC, shamisp commented
@yosefe I think this has to be back ported to 1.10.x ?

2021-02-04 14:57 UTC, yosefe commented
> @yosefe I think this has to be back ported to 1.10.x ?

it's up to @dsharma283

2021-02-04 15:32 UTC, dsharma283 commented
> 
> 
> > @yosefe I think this has to be back ported to 1.10.x ?
> 
> it's up to @dsharma283

I can do that, it is good to have.

2021-02-04 16:13 UTC, shamisp commented
thanks, please open PR for v1.10.x branch. Much appreciated.

2021-02-04 16:14 UTC, shamisp commented
@dmitrygx Is it good to go? thanks !

2021-02-04 16:51 UTC, dmitrygx approved these changes

2021-02-04 19:09 UTC, merged