API/UCT/IFACE: added keepalive_timeout value
openucx/ucx pull request #5992
Opened 2020-12-07 11:14 UTC by hoopoepg

## What
- extended uct_iface_params structure

## Why ?
- to allow synchronize UCT/UCP keepalive timeout intervals

## How ?
- added keepalive_timeout value to uct_iface_params structure

2020-12-07 14:35 UTC, shamisp commented
@hoopoepg - do you have code demonstrating how it will be used and implemented ?

2020-12-07 15:07 UTC, hoopoepg commented
Not yet. It will be used to configure TCP keepalive timeout, for instance

2020-12-07 17:14 UTC, hoopoepg commented
@shamisp there is uct_tcp_iface::config::keepalive::idle value which may be initialized by "auto" value, in this case keepalive timeout will be initialized by value from uct_iface_params::keepalive_timeout

2020-12-07 17:18 UTC, hoopoepg commented
/azp run

2020-12-07 17:55 UTC, shamisp commented
you mentioned `synchronize UCT/UCP` - Is there UCP level value that you want to propagate to UCT ? Do you need to query the value first from the transports before synchronizing UCP across multiple UCTs ?

2020-12-07 17:59 UTC, hoopoepg commented
I mean set UCT built-in (TCP for instance) keepalive parameters based on UCP data

2020-12-07 19:04 UTC, shamisp commented
> based on UCP data across all ifaces
So I guess you query it first ? If so where/how. thanks.

2020-12-07 19:19 UTC, yosefe commented on src/uct/api/uct.h
> +    ucs_time_t                                   keepalive_timeout;
keepalive_timeout -> keepalive_interval

2020-12-07 19:26 UTC, hoopoepg commented
> So I guess you query it first ? If so where/how. thanks.

it is configured using "KEEPALIVE_TIMEOUT" runtime variable

2020-12-07 19:29 UTC, hoopoepg commented on src/uct/api/uct.h
> +    ucs_time_t                                   keepalive_timeout;
renamed to keepalive_interval

2020-12-07 19:31 UTC, yosefe approved these changes

2020-12-07 21:16 UTC, shamisp commented
> > So I guess you query it first ? If so where/how. thanks.
> 
> it is configured using "KEEPALIVE_TIMEOUT" runtime variable

Okay, so what you are trying to say is that UCP will read the configure value and will propagate to all relevant transport ? Is not keep alive transport specific. A.k.a the value is driven by the transport and not UCP ? thanks

2020-12-08 03:22 UTC, shamisp approved these changes

2020-12-08 10:56 UTC, yosefe commented
@tonycurtis can you pls take a look?

2020-12-08 14:02 UTC, tonycurtis requested changes
1059-1060: indicate time units?

2020-12-08 14:05 UTC, hoopoepg commented
it is actual time interval stored in time units

2020-12-09 06:26 UTC, brminich approved these changes

2020-12-09 08:57 UTC, hoopoepg commented
@yosefe ok to merge?

2020-12-10 12:48 UTC, hoopoepg commented
@tonycurtis more comments?

2020-12-10 23:10 UTC, tonycurtis approved these changes

2020-12-11 10:32 UTC, merged