UCP: call user callback on ucp_ep_close_nbx.
openucx/ucx pull request #6036
Opened 2020-12-16 14:07 UTC by petro-rudenko

## What
Use user passed params for `ucp_ep_flush_internal` in `ucp_ep_close_nbx` to handle callback and user data fields.

## Why ?
To unify ucp API, and makes easier to implement JUCX logic.

2020-12-17 10:18 UTC, petro-rudenko commented
/azp run

2020-12-17 14:21 UTC, yosefe commented on src/ucp/api/ucp.h
> +                                              with a UCP_OP_ATTR_FLAG_NO_IMM_CMPL,
`with @ref UCP_OP_ATTR_FLAG_NO_IMM_CMPL`

2020-12-17 14:21 UTC, yosefe commented on test/gtest/ucp/test_ucp_wireup.cc
> +UCS_TEST_P(test_ucp_wireup_2sided, close_nbx_callback) {
👍

2020-12-18 12:31 UTC, yosefe approved these changes

2020-12-18 12:31 UTC, yosefe commented
@tonycurtis can you pls take a look on small doc change?

2020-12-18 12:32 UTC, yosefe commented
bot:pipe:retest

2020-12-18 13:54 UTC, tonycurtis requested changes
ucp.h:289: immediate

2020-12-18 14:46 UTC, petro-rudenko commented
Fixed

2020-12-18 15:53 UTC, petro-rudenko commented
iodemo (No traffic)

/azp run

2020-12-19 12:10 UTC, yosefe commented
bot:pipe:retest

2020-12-27 16:55 UTC, merged