UCT/IB/RC: Implemented AM short IOV in RC verbs.
openucx/ucx pull request #6052
Opened 2020-12-18 18:22 UTC by rakhmets

## What
Implemented uct_tcp_ep_am_short_iov in RC verbs.

uct_tcp_ep_am_short_iov is an interface for sending IO vector using short communication operation.

2020-12-18 23:28 UTC, dmitrygx requested changes

2020-12-18 23:28 UTC, dmitrygx commented on src/uct/ib/rc/verbs/rc_verbs_ep.c
> +    uint32_t length             = uct_iov_total_length(iov, iovcnt);
pls, calculate the IOV total length where it is used, i.e. as a parameter to `UCT_RC_CHECK_AM_SHORT()`
to avoid the overhead for release build

2020-12-18 23:28 UTC, dmitrygx commented on src/uct/ib/rc/verbs/rc_verbs_ep.c
> +    sge[0].length = sizeof(uct_rc_hdr_t);
`UCS_STATIC_ASSERT(sizoef(id) == sizeof(uct_rc_hdr_t))`

2020-12-18 23:28 UTC, dmitrygx commented on src/uct/ib/rc/verbs/rc_verbs_ep.c
> +    struct ibv_send_wr wr;
can we re-use `inl_am_wr` + `inl_sge[UCT_IB_MAX_IOV]` (common for both AM Short operations) for AM Short IOV? but need to set `sge_cnt`

if it is impossible:
what about defining `inl_am_iov_wr` + `inl_sge[UCT_IB_MAX_IOV]` (common for both AM Short operations) for AM Short IOV?

2020-12-18 23:44 UTC, dmitrygx commented
> Implemented uct_tcp_ep_am_short_iov in RC verbs.

pls, fix the description

2020-12-19 12:10 UTC, yosefe commented
bot:pipe:retest

2020-12-25 17:07 UTC, yosefe commented on src/uct/ib/rc/verbs/rc_verbs_impl.h
> +    iface->inl_sge[0].addr   = (uintptr_t)&id;
IMO better use a local var for RC header and assign 'id' to rc_hdr.id

2020-12-28 13:52 UTC, rakhmets commented
/azp run

2020-12-28 19:56 UTC, rakhmets commented
/azp run

2020-12-29 09:53 UTC, yosefe approved these changes

2020-12-29 10:20 UTC, brminich approved these changes

2020-12-29 11:44 UTC, dmitrygx approved these changes

2020-12-29 16:22 UTC, rakhmets commented
bot:pipe:retest

2020-12-29 21:42 UTC, merged