DOC/RECV-NBX: removed incorrect note - v1.10
openucx/ucx pull request #6114
Opened 2021-01-11 19:46 UTC by hoopoepg

- removed incorrect note from function description

(cherry picked from commit 4b4df04074e57bf82005c08fa2a9a802d9034413)

backport from https://github.com/openucx/ucx/pull/6104

2021-01-11 21:10 UTC, hoopoepg commented
infra issue

2021-01-11 21:10 UTC, hoopoepg commented
/azp run

2021-01-13 10:17 UTC, yosefe commented
/azp run

2021-01-13 15:00 UTC, yosefe commented
@shamisp @tonycurtis can you pls take a look? this is a backport to v1.10

2021-01-13 15:00 UTC, yosefe approved these changes

2021-01-13 15:05 UTC, tonycurtis requested changes
not part of removed text, but l. 3382: drop last "to".

2021-01-13 15:17 UTC, hoopoepg commented
@tonycurtis https://github.com/openucx/ucx/pull/6128

2021-01-13 15:55 UTC, shamisp commented
👍

2021-01-13 15:55 UTC, merged