UCT/SM/SELF: Implemented AM short IOV for self transport.
openucx/ucx pull request #6191
Opened 2021-01-25 17:37 UTC by rakhmets

## What
Implemented uct_ep_am_short_iov for self transport.

uct_ep_am_short_iov is an interface for sending IO vector using short communication operation.

2021-01-25 18:06 UTC, yosefe approved these changes

2021-01-25 18:06 UTC, dmitrygx requested changes

2021-01-25 18:06 UTC, dmitrygx commented on src/uct/sm/self/self.c
> +    UCT_TL_EP_STAT_OP(&ep->super, AM, SHORT, uct_iov_total_length(iov, iovcnt));
`UCT_TL_EP_STAT_OP(&ep->super, AM, SHORT, length);`

2021-01-25 18:29 UTC, dmitrygx approved these changes

2021-01-26 06:15 UTC, brminich approved these changes

2021-01-26 20:09 UTC, merged