AZP: Fix 2 publish artefacts
openucx/ucx pull request #6302
Opened 2021-02-09 15:20 UTC by avildema

Fix 2 publish artefacts

2021-02-09 15:27 UTC, yosefe commented on buildlib/coverity.yml
> +            touch $cov_error_folder/index.html
remove later?

2021-02-09 15:43 UTC, avildema commented on buildlib/coverity.yml
> +            touch $cov_error_folder/index.html
sure, need for check

2021-02-09 16:09 UTC, yosefe requested changes
publish still fails

2021-02-09 18:21 UTC, avildema commented
> publish still fails

success
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=13488&view=logs&j=42a93636-9ba0-5067-13f1-66c03328bbdd&t=df4a274b-b6f3-5f2f-7dce-3379527e6707

2021-02-10 08:15 UTC, yosefe commented
@avildema can you pls push some test commit for C code check error (for example, remove some coverity[] suppressions) to show artifacts are generated?

2021-02-10 08:25 UTC, avildema commented
> @avildema can you pls push some test commit for C code check error (for example, remove some coverity[] suppressions) to show artifacts are generated?

@yosefe I do it direct in coverity test, link on test with artefact in top

2021-02-10 11:50 UTC, avildema commented
> @avildema can you pls push some test commit for C code check error (for example, remove some coverity[] suppressions) to show artifacts are generated?

@yosefe https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=13514&view=artifacts&pathAsName=false&type=publishedArtifacts

all work

2021-02-10 15:21 UTC, yosefe commented
> > @avildema can you pls push some test commit for C code check error (for example, remove some coverity[] suppressions) to show artifacts are generated?
> 
> @yosefe https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=13514&view=artifacts&pathAsName=false&type=publishedArtifacts
> 
> all work

Looks good!
but why do we have Coverity on althca? shouldn't we remove coverity from test_jenkins.sh?

2021-02-10 19:19 UTC, avildema commented
> > > @avildema can you pls push some test commit for C code check error (for example, remove some coverity[] suppressions) to show artifacts are generated?
> > 
> > 
> > @yosefe https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=13514&view=artifacts&pathAsName=false&type=publishedArtifacts
> > all work
> 
> Looks good!
> but why do we have Coverity on althca? shouldn't we remove coverity from test_jenkins.sh?

of course , in next PR, will remove build and coverity sections, if want can remove in this PR

2021-02-10 19:22 UTC, yosefe commented
> of course , in next PR, will remove build and coverity sections, if want can remove in this PR

sure, can be next pr

2021-02-10 19:26 UTC, yosefe approved these changes

2021-02-11 06:24 UTC, avildema commented
bot:pipe:retest

2021-02-11 09:24 UTC, merged