UCP: Add ucp_lib_query API - New PR
openucx/ucx pull request #6552
Opened 2021-03-24 14:56 UTC by lappazos

## What
Add ucp_lib_query API in order to query lib thread mode support 

## Why ?
We would like to add an api to query the lib thread mode before ucp_context+ucp_worker Are created. This is required for UCC - there the “thread_mode” is a property of ucc_lib_info_t object. User creates lib_info with the required thread_mode and then can create different ucc_context_t from the lib object. Ucp_worker is created when ucc_context is created, ie after the lib object is allocated

## How ?
Query thread mode according to UCX MT compilation flag

2021-03-24 14:56 UTC, lappazos commented
instead of https://github.com/openucx/ucx/pull/6517

2021-03-24 15:10 UTC, lappazos commented
@yosefe @shamisp @tonycurtis @brminich sorry about the confusion, i had no way to salvage the old PR, my error during squash. this 1 commit is the squash of all other commits in the previous PR.
please, review again and approve.
And please add the API label again, i have no permissions.

2021-03-24 15:34 UTC, tonycurtis commented on src/ucp/api/ucp.h
> + * the Library.
attributes that characterize the library.

2021-03-24 15:35 UTC, tonycurtis commented on src/ucp/api/ucp.h
> +    /**< UCP library maximal supported thread level flag */
"maximal" here, "maximum" later on.  suggest using "maximum" everywhere (more common usage)

2021-03-24 15:36 UTC, tonycurtis requested changes

2021-03-24 15:36 UTC, tonycurtis commented on src/ucp/api/ucp.h
> +     * throughout the lifetime of the library. Accordingly, user can call
... the user ...

2021-03-24 16:06 UTC, yosefe approved these changes

2021-03-24 16:06 UTC, yosefe commented on src/ucp/api/ucp.h
> + * @brief UCP lib attributes field mask.
lib -> library

2021-03-24 17:10 UTC, shamisp commented
Please add news entry

2021-03-24 19:56 UTC, lappazos commented
> Please add news entry

added. @shamisp please review and approve. sorry for the force push, had to because my NEWS file in my branch wasn't updated and needed to pull and merge

2021-03-24 21:29 UTC, shamisp commented
Looks good.

2021-03-25 08:30 UTC, yosefe approved these changes
pls squash

2021-03-25 12:54 UTC, yosefe approved these changes

2021-03-25 19:46 UTC, merged