UCP/API: Replaced 'maximal' by 'maximum' in UCP/API docs.
openucx/ucx pull request #6609
Opened 2021-04-02 12:28 UTC by rakhmets

## What
Replaced 'maximal' by 'maximum' in UCP/API docs.

## Why ?
The changes are required to make the documentation more consistent.
The changes were requested in these review comments:
https://github.com/openucx/ucx/pull/6557#discussion_r604469311
https://github.com/openucx/ucx/pull/6557#pullrequestreview-626636615

2021-04-03 09:57 UTC, yosefe approved these changes

2021-04-03 09:57 UTC, yosefe commented
@tonycurtis can you pls take a look

2021-04-03 16:37 UTC, tonycurtis requested changes

2021-04-03 16:37 UTC, tonycurtis commented on src/ucp/api/ucp.h
> + * @param [in]   max_eps   Maximum number of endpoints which should be filled
which -> that

2021-04-05 05:56 UTC, brminich approved these changes

2021-04-05 07:19 UTC, rakhmets commented on src/ucp/api/ucp.h
> + * @param [in]   max_eps   Maximum number of endpoints which should be filled
done

2021-04-06 16:06 UTC, rakhmets commented
@tonycurtis could you please to approve the changes if everything is ok

2021-04-06 16:16 UTC, tonycurtis approved these changes

2021-04-09 07:20 UTC, merged