TOOLS/PERF: Add error handling option to perftest
openucx/ucx pull request #6633
Opened 2021-04-08 14:26 UTC by brminich

## What
Add error handling support to UCX perftest

## Why ?
To measure performance using eps created with error handling support (which simulates various client-server applications).
Not all the transports support error handling, which noticeable accepts performance.
For instance:
No error handling support
```
$UCX_LOG_LEVEL=info ./src/tools/perf/ucx_perftest  -t tag_lat  localhost
[1617891327.753542] [jazz18:56657:0]      ucp_worker.c:1884 UCX  INFO    ep_cfg[0]: tag(posix/memory knem/memory rc_mlx5/mlx5_0:1);
[1617891327.753544] [jazz18:56685:0]      ucp_worker.c:1884 UCX  INFO    ep_cfg[0]: tag(posix/memory knem/memory rc_mlx5/mlx5_0:1);
```

With error handling support:
```
[1617891296.290892] [jazz18:56608:0]      ucp_worker.c:1884 UCX  INFO    ep_cfg[0]: tag(rc_mlx5/mlx5_0:1 rc_mlx5/mlx5_4:1);
[1617891296.290902] [jazz18:56576:0]      ucp_worker.c:1884 UCX  INFO    ep_cfg[0]: tag(rc_mlx5/mlx5_0:1 rc_mlx5/mlx5_4:1);
```

2021-04-08 14:29 UTC, hoopoepg approved these changes

2021-04-09 08:03 UTC, brminich commented
@yosefe, can you please review?

2021-04-09 08:30 UTC, dmitrygx approved these changes

2021-04-11 08:33 UTC, yosefe approved these changes

2021-04-11 08:34 UTC, yosefe requested changes
pls one test with err handling mode to test_ucp_perf.cc

2021-04-14 12:33 UTC, dmitrygx approved these changes

2021-04-15 05:56 UTC, brminich commented
@yosefe, added test

2021-04-15 13:28 UTC, yosefe approved these changes

2021-04-16 07:21 UTC, brminich commented
@yosefe, ok to merge?

2021-04-16 11:09 UTC, merged