DOCS/COMMENTS: fixed typos
openucx/ucx pull request #6664
Opened 2021-04-15 09:46 UTC by hoopoepg

2021-04-15 09:48 UTC, brminich approved these changes

2021-04-15 11:36 UTC, hoopoepg commented
bot:pipe:retest

2021-04-15 13:22 UTC, shamisp commented
👍  @tonycurtis please take a look. thanks

2021-04-15 13:29 UTC, tonycurtis requested changes

2021-04-15 13:29 UTC, tonycurtis commented on src/ucp/api/ucp.h
> + *       for transferring latency-critical amount of data.
transferring a latency-critical...

2021-04-15 13:29 UTC, tonycurtis commented on src/ucp/api/ucp.h
> + * InfiniBand and Aries key.
Confusing.

2021-04-15 13:29 UTC, tonycurtis commented on src/uct/ib/dc/dc_mlx5_ep.c
> +    /* No any other pending operations (except no-op, flush(CANCEL), and others
"No any"?

2021-04-15 13:29 UTC, tonycurtis commented on src/uct/ib/dc/dc_mlx5_ep.c
>       * which don't consume TX resources) allowed to be still scheduled on an
which -> that

2021-04-15 13:29 UTC, tonycurtis commented on src/ucp/api/ucp.h
>   *       attributes by @ref ucp_worker_query routine.
by the @ref ...

2021-04-15 13:40 UTC, hoopoepg commented on src/ucp/api/ucp.h
> + *       for transferring latency-critical amount of data.
updated

2021-04-15 13:40 UTC, hoopoepg commented on src/ucp/api/ucp.h
>   *       attributes by @ref ucp_worker_query routine.
fixed

2021-04-15 13:43 UTC, hoopoepg commented on src/uct/ib/dc/dc_mlx5_ep.c
> +    /* No any other pending operations (except no-op, flush(CANCEL), and others
re-worded

2021-04-15 13:43 UTC, hoopoepg commented on src/uct/ib/dc/dc_mlx5_ep.c
>       * which don't consume TX resources) allowed to be still scheduled on an
updated

2021-04-15 20:00 UTC, yosefe approved these changes

2021-04-16 07:30 UTC, hoopoepg commented
@yosefe ok to merge?

2021-04-16 07:57 UTC, brminich commented
@tonycurtis, do you have other comments?

2021-04-16 13:32 UTC, tonycurtis approved these changes

2021-04-16 15:08 UTC, merged