TOOLS/PERF: Fix run_stream_uni
openucx/ucx pull request #6951
Opened 2021-06-15 16:25 UTC by yiyuanliu

Set sn to 0 before run UCX_PERF_CMD_PUT.

## What/Why

When test `ucp_put`, `run_stream_uni` use `sn = 0` to indicate the completion of the last iteration. In multiple rounds of testing, sn must be set to 0 before the start of test. Without this fix, `ucx_perftest -t ucp_put_bw` will get wrong results with ud transport.

```
# before fix
➜  ucx git:(master) ✗ UCX_NET_DEVICES=mlx4_0:1 UCX_TLS=ud ./install-debug/bin/ucx_perftest t04 -t ucp_put_bw -s 409600
[1623772525.376478] [tstore04:5596 :0]        perftest.c:1581 UCX  WARN  CPU affinity is not set (bound to 24 cpus). Performance may be impacted.
+--------------+--------------+-----------------------------+---------------------+-----------------------+
|              |              |      overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | typical | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
[thread 0]               133     0.000  7538.510  7538.510       51.82      51.82         133         133
[thread 0]               268     0.000  7490.474  7514.313       52.15      51.98         134         133
[thread 0]               403     0.000  7421.667  7483.278       52.63      52.20         135         134

# after fix
➜  ucx git:(master) ✗ UCX_NET_DEVICES=mlx4_0:1 UCX_TLS=ud ./install-debug/bin/ucx_perftest t04 -t ucp_put_bw -s 409600
[1623773120.727365] [tstore04:28530:0]        perftest.c:1581 UCX  WARN  CPU affinity is not set (bound to 24 cpus). Performance may be impacted.
+--------------+--------------+-----------------------------+---------------------+-----------------------+
|              |              |      overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | typical | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
[thread 0]             11777    90.122    84.911    84.911     4600.40    4600.40       11777       11777
[thread 0]             23798    91.145    83.192    84.043     4695.46    4647.93       12020       11899
```

2021-06-15 16:29 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2021-06-15 16:41 UTC, yosefe commented on src/tools/perf/lib/ucp_tests.cc
> +        if (CMD == UCX_PERF_CMD_PUT) {
pls add a new method "reset_buffers()" to wrap the code in 532-537 (but also reset the receive buffer) and use it here. the code in 532-537 is GPU-safe.

2021-06-15 16:41 UTC, yosefe commented
ok to test

2021-06-15 18:18 UTC, shamisp commented
@yiyuanliu - Thanks for the patch ! May I ask what organization do you represent ? FYI, for accepting code contributions we require to sign CLA https://www.openucx.org/license/

2021-06-15 18:18 UTC, shamisp requested changes
Pending on CLA

2021-06-18 13:19 UTC, yosefe commented
bot:pipe:retest

2021-06-18 13:20 UTC, yosefe commented
bot:pipe:retest

2021-06-21 11:06 UTC, yiyuanliu commented
> @yiyuanliu - Thanks for the patch ! May I ask what organization do you represent ? FYI, for accepting code contributions we require to sign CLA https://www.openucx.org/license/

I am currently a thrid year graduate student of Tsinghua University, and I will graduate in July and join a research institution. I think I may not be suitable for signing a CLA at the moment. But the bug involved in this patch are easy to fix, and I hope it can be fixed by other authorized persons.

2021-07-04 07:58 UTC, yosefe commented
@yiyuanliu this fix was merged in #7013, so I think this PR can be closed

2021-07-04 07:59 UTC, closed without merging