AUTHORS: affiliation change
openucx/ucx pull request #7223
Opened 2021-08-11 16:09 UTC by alex--m

Signed-off-by: Alex Margolin <alex.margolin@huawei.com>

2021-08-11 16:09 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2021-08-11 16:32 UTC, shamisp approved these changes

2021-08-11 16:36 UTC, shamisp requested changes
@alex--m FYI, we will need a new CLA from you

2021-08-17 11:24 UTC, alex--m commented
This is odd... does this mean I'm affiliated with Huawei until further notice?

2021-08-17 14:44 UTC, shamisp commented
Your previous contributions are affiliated with Huawei.  You can sign a
personal CLA while the things get sorted out.

On Tue, Aug 17, 2021 at 6:25 AM Alex Margolin ***@***.***>
wrote:

> This is odd... does this mean I'm affiliated with Huawei until further
> notice?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/openucx/ucx/pull/7223#issuecomment-900214067>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARB5WDEKHZF7CFCQH5YOFLT5JBJHANCNFSM5B64MIXQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2026-07-02 13:37 UTC, gleon99 commented
Hi @alex--m - we're cleaning up the UCX PR backlog and plan to close this PR in 7 days. Please let us know if you'd like to keep it open.

2026-07-19 13:22 UTC, closed without merging