GTEST: A workaround for the GCC issue in FC35
openucx/ucx pull request #7721
Opened 2021-11-28 17:16 UTC by shamisp

Fixes #7705

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

2021-11-28 17:39 UTC, swx-jenkins3 commented
Can one of the admins verify this patch?

2021-11-28 17:40 UTC, yosefe approved these changes

2021-11-28 20:01 UTC, yosefe requested changes

2021-11-28 20:01 UTC, yosefe commented on test/gtest/uct/uct_test.cc
> +            local_fd.fd   = ucs_async_pipe_rfd(&aux_pipe);
@shamisp this causes fd leaks and test failures
need to set wakeup_fd here. and copy to local_fd right before calling poll()

2021-11-29 07:13 UTC, brminich commented on test/gtest/uct/uct_test.cc
> +    /* Caching fd locally to workaroud bug in gcc (GCC) 11.2.1 20210728 FC35
`workaround`

2021-12-01 13:57 UTC, shamisp commented
@yosefe merge ?

2021-12-01 15:32 UTC, yosefe approved these changes

2021-12-01 20:25 UTC, merged