UCT/EP: move local_sockaddr to end of uct_ep_params_t to fix ABI break
openucx/ucx pull request #7870
Opened 2022-01-25 08:54 UTC by ybedbug

What
[PR #7623](https://github.com/openucx/ucx/pull/7623) breaks UCT ABI because the new field local_sockaddr was added to the middle of uct_ep_params_t struct. Need to move it to the end.

Why ?
Fix UCT ABI break

How ?
move local_sockaddr to the end of uct_ep_params_t.

2022-01-25 11:30 UTC, yosefe approved these changes

2022-01-25 11:30 UTC, yosefe commented
cc @shamisp @tonycurtis

2022-01-25 12:52 UTC, tonycurtis requested changes

2022-01-25 12:52 UTC, tonycurtis commented on src/uct/api/uct.h
> +     * will create an endpoint binding with this local sockaddr.
with -> to

2022-01-25 13:32 UTC, shamisp reviewed
Other than the issue Tony highlighted it looks ok

2022-01-25 23:42 UTC, ybedbug commented on src/uct/api/uct.h
> +     * will create an endpoint binding with this local sockaddr.
fixed

2022-01-27 08:22 UTC, yosefe reviewed
pls squash

2022-01-27 08:22 UTC, yosefe approved these changes

2022-01-27 18:00 UTC, yosefe commented
test is completed successfully but github status not updated -- merging

2022-01-27 18:00 UTC, merged