DOCS/FAQ: re-worded static build section
openucx/ucx pull request #8141
Opened 2022-04-21 09:08 UTC by hoopoepg

- re-worded some text in static build section

2022-04-24 10:11 UTC, yosefe approved these changes

2022-05-02 07:21 UTC, yosefe commented
@tonycurtis @shamisp can you pls take a look?

2022-05-02 13:21 UTC, shamisp requested changes
@tonycurtis  ?

2022-05-02 13:21 UTC, shamisp commented on docs/source/faq.md
> +When linking with static UCX libraries, the user needs to list all required
needs -> must

2022-05-02 13:21 UTC, shamisp commented on docs/source/faq.md
> +knem transports, the user can use:
have to use:

2022-05-02 13:32 UTC, tonycurtis submitted a review, later dismissed

2022-05-03 09:25 UTC, hoopoepg commented on docs/source/faq.md
> +When linking with static UCX libraries, the user needs to list all required
updated

2022-05-03 09:25 UTC, hoopoepg commented on docs/source/faq.md
> +knem transports, the user can use:
updated

2022-05-03 13:05 UTC, shamisp approved these changes

2022-05-07 07:15 UTC, hoopoepg commented
@yosefe ok to merge?

2022-05-07 14:22 UTC, shamisp commented
@hoopoepg it is good to go.

2022-05-08 08:15 UTC, merged