JUCX: Implement arm() and getEventFD() in UcpWorker
openucx/ucx pull request #8453
Opened 2022-08-15 14:05 UTC by fruhland

## What
Implement the methods `UcpWorker.arm()` and `UcpWorker.getEventFD()` in JUCX, which call the native methods `ucp_worker_arm()` and `ucp_worker_get_efd()`.

## Why ?
Currently, polling a worker with JUCX using the wakeup mechanism is only possible by first calling `UcpWorker.waitForEvents()`, which blocks until the next event on that worker occurs, and then calling `UcpWorker.progress()`. However, this does not work well for programs, which use multiple workers, since it is not possible to call `UcpWorker.waitForEvents()` on multiple workers at the same time. A solution for this problem is to use an epoll file descriptor (e.g. with the help of [this](https://github.com/helins/linux-epoll.java) library), but for doing so, it is necessary to get each worker's event file descriptor and re-arm each worker after events have been polled. The native UCP library already provides these functions and this PR just makes them accessible from Java.

2022-08-16 08:10 UTC, petro-rudenko requested changes
Can you please add some tests

2022-08-16 09:04 UTC, fruhland commented
I implemented one test, wich checks if the event file descriptor is not 0 and another, which just calls `UcpWorker.arm()` and passes, if no exception is thrown. To really test the functionality of `arm()`, it would be necessary to first manually poll the worker's event file descriptor and then re-arm the worker. However, this is not possible without an external library, so I think it is better to just have this simple test.

2022-08-17 08:17 UTC, yosefe commented
@fruhland thank you for your contribution! UCX requires signing a CLA in order to submit code to upstream (see https://github.com/openucx/ucx/wiki/Guidance-for-contributors).
cc @shamisp

2022-08-20 08:48 UTC, yosefe commented
@petro-rudenko can you pls re-review?

2022-08-20 09:33 UTC, petro-rudenko commented
Can you please test both `arm()` and `getEventFd` in a single test, to save test time.

2022-08-20 10:47 UTC, petro-rudenko submitted a review, later dismissed

2022-08-20 10:49 UTC, fruhland commented on bindings/java/src/test/java/org/openucx/jucx/UcpWorkerTest.java
> +        worker.close();
I combined both tests into a single one with my latest commit.

2022-08-21 13:30 UTC, yosefe approved these changes

2022-08-30 11:17 UTC, fruhland commented
Is there still anything, keeping this PR from being merged? Please let me know, if I should implement further changes.

2022-08-30 13:41 UTC, shamisp commented
> Is there still anything, keeping this PR from being merged? Please let me know, if I should implement further changes.

@fruhland We are waiting for the signed CLA. Have you emailed it ? thanks

2022-08-30 14:14 UTC, fruhland commented
> > Is there still anything, keeping this PR from being merged? Please let me know, if I should implement further changes.
> 
> @fruhland We are waiting for the signed CLA. Have you emailed it ? thanks

Yes, I sent it to `admin@ucfconsortium.org`, as described in the int contribution guide.

2022-08-31 00:12 UTC, shamisp commented
@yosefe @fruhland  - we are good on CLA. thanks

2022-08-31 08:01 UTC, yosefe commented
@fruhland can you pls squash?

2022-09-01 07:51 UTC, fruhland commented
> @fruhland can you pls squash?

All changes are now squashed into a single commit.

2022-09-04 15:17 UTC, yosefe approved these changes

2022-09-04 15:17 UTC, merged