AZP: add to CI gtest with proto enable
openucx/ucx pull request #8509
Opened 2022-09-07 14:00 UTC by avildema

add to CI gtest with proto enable eq yes

2022-09-07 14:09 UTC, yosefe commented on contrib/test_jenkins.sh
> +	run_test_proto_enable
we can still do check_machine

2022-09-07 20:46 UTC, evgeny-leksikov requested changes
CI has been failed with error. Can we report it as a warning?

2022-09-09 08:15 UTC, evgeny-leksikov approved these changes

2022-09-09 13:28 UTC, yosefe commented on contrib/test_jenkins.sh
> +	run_test_proto_enable
```sh
if [ -n "$JENKINS_RUN_TESTS" ] || [ -n "$RUN_TESTS" ]
    check_machine
    if [[ "$PROTO_ENABLE" == "yes" ]]; then
        run_test_proto_enable
    else
        run_tests
    fi
fi
```

2022-09-09 13:28 UTC, yosefe commented on contrib/test_jenkins.sh
> +	run_test_proto_enable
@avildema pls squash + force push due to small PR

2022-09-09 19:50 UTC, yosefe approved these changes

2022-09-11 07:39 UTC, merged