UCS: Add missing ZHAOXIN cpu bandwith
openucx/ucx pull request #8559
Opened 2022-09-23 09:03 UTC by skypexu

## What
CPU bandwidth for ZHAOXIN is missing
The function ucs_cpu_get_memcpy_bw can be out of array range.
```
double ucs_cpu_get_memcpy_bw()                                                  
{                                                                               
    return ucs_cpu_est_bcopy_bw[ucs_arch_get_cpu_vendor()];                     
}  
```

## How ?
Add bandwidth for it.

2022-09-23 09:08 UTC, hoopoepg commented on src/ucs/arch/cpu.c
> +    [UCS_CPU_VENDOR_ZHAOXIN] = 5800 * UCS_MBYTE
please align by columns on lines above

2022-09-24 03:39 UTC, skypexu commented on src/ucs/arch/cpu.c
> +    [UCS_CPU_VENDOR_ZHAOXIN] = 5800 * UCS_MBYTE
Fixed

2022-09-24 06:47 UTC, hoopoepg approved these changes

2022-09-24 14:07 UTC, shamisp requested changes
@skypexu , since you are the first time contributor we need signed CLA, unless you represent organization that has corporate signed CLA.  CLA can be found here https://github.com/openucx/ucx/pull/8529

2022-09-25 08:07 UTC, yosefe commented
@shamisp does this CLA cover it?
https://github.com/openucx/ucx/pull/5912#issuecomment-731474111

2022-09-25 08:07 UTC, yosefe approved these changes

2022-09-25 16:06 UTC, yosefe commented
/azp run

2022-09-26 12:55 UTC, shamisp commented
> @shamisp does this CLA cover it?
> [#5912 (comment)](https://github.com/openucx/ucx/pull/5912#issuecomment-731474111)

Depends if it is personal or corporate. I will check.

2022-09-27 13:26 UTC, shamisp commented
ZHAOXIN has corporate agreement. We are all clear.

2022-09-27 13:26 UTC, shamisp approved these changes

2022-09-27 15:53 UTC, merged