UCP/API/TOOLS: Specify memory type when allocating with ucx_info tool
openucx/ucx pull request #8579
Opened 2022-09-30 07:52 UTC by yosefe

2022-09-30 08:03 UTC, hoopoepg submitted a review, later dismissed

2022-10-01 07:18 UTC, yosefe commented
@shamisp @tonycurtis can you pls take a look?

2022-10-01 15:15 UTC, shamisp requested changes

2022-10-01 15:15 UTC, shamisp commented on src/tools/info/ucx_info.c
> +    printf("  -m <size>[,<type>]   Show UCP memory allocation info for a given size and type\n");
Can we list in the help message supported types ?

2022-10-01 15:15 UTC, shamisp commented on src/ucp/core/ucp_mm.c
> +        printf("<Failed to allocate memory of size %zd>\n", mem_size_value);
memory of size XX type YY

2022-10-01 15:15 UTC, shamisp commented on src/ucp/core/ucp_mm.c
> +            printf("<Invalid memory type '%s'>\n", mem_type_str);
"<Invalid memory type '%s' , supported types: %s>\n"

2022-10-01 17:17 UTC, tonycurtis requested changes

2022-10-01 17:17 UTC, tonycurtis commented on src/tools/info/ucx_info.c
>      printf("At least one of the following options has to be set:\n");
must be set?

2022-10-01 21:16 UTC, yosefe commented
@shamisp @tonycurtis your comments were applied, can you pls check again?

2022-10-02 00:56 UTC, shamisp approved these changes

2022-10-02 16:24 UTC, yosefe commented
@hoopoepg can you pls re-review?

2022-10-03 06:27 UTC, hoopoepg submitted a review, later dismissed

2022-10-04 08:59 UTC, merged