UCT/API/CUDA/INFO: Implement dmabuf export
openucx/ucx pull request #8581
Opened 2022-09-30 09:58 UTC by yosefe

2022-09-30 10:02 UTC, hoopoepg submitted a review, later dismissed

2022-10-02 07:00 UTC, yosefe commented
@Akshay-Venkatesh  can you pls review?

2022-10-03 16:21 UTC, brminich approved these changes

2022-10-03 17:06 UTC, Akshay-Venkatesh approved these changes

2022-10-04 17:19 UTC, yosefe commented on src/uct/cuda/cuda_copy/cuda_copy_md.c
> +    cu_err = cuDeviceGet(&cuda_device, 0);
@Akshay-Venkatesh fixed

2022-10-04 17:20 UTC, yosefe commented
@tonycurtis @shamisp  can you pls review the documentation?

2022-10-04 17:25 UTC, tonycurtis requested changes

2022-10-04 17:25 UTC, tonycurtis commented on docs/source/faq.md
> +o be loaded, or (starting with UCX v1.14) dmabuf support on the system.
to be loaded

2022-10-04 17:25 UTC, tonycurtis commented on src/uct/api/uct.h
> +     * If the md does not support querying fd object associated with the region,
the fd object

2022-10-04 17:25 UTC, tonycurtis commented on src/uct/api/uct.h
> +     * is the responsibility of the user to close returned fd once used using
the returned fd

2022-10-04 17:25 UTC, tonycurtis commented on src/uct/api/uct.h
> +     * close (2).
"used using" needs different phrasing

2022-10-05 15:44 UTC, yosefe commented on docs/source/faq.md
> +- UCX v1.14 or later.
why? it's a version number, not a branch name

2022-10-05 15:46 UTC, shamisp commented on docs/source/faq.md
> +- UCX v1.14 or later.
If you insist - > 1.14.0

2022-10-05 15:56 UTC, yosefe commented on docs/source/faq.md
> +- UCX v1.14 or later.
done

2022-10-05 17:58 UTC, shamisp submitted a review, later dismissed

2022-10-05 18:08 UTC, yosefe commented
@Akshay-Venkatesh can you pls take a look?

2022-10-07 22:49 UTC, Akshay-Venkatesh submitted a review, later dismissed

2022-10-08 17:34 UTC, merged