UCP/RNDV: Remove async blocking
openucx/ucx pull request #8925
Opened 2023-03-09 11:58 UTC by Artemy-Mellanox

## Why ?
Fixing internal issue [3283063](https://redmine.mellanox.com/issues/3283063)

## How ?
Remove unnecessary async lock which otherwise would block UD progress.

2023-03-09 12:01 UTC, yosefe approved these changes

2023-03-09 12:01 UTC, yosefe requested changes

2023-03-09 12:01 UTC, yosefe commented on src/ucp/rndv/rndv.c
> +    return;
remove this?

2023-03-09 14:57 UTC, brminich approved these changes

2023-03-10 12:33 UTC, brminich submitted a review, later dismissed

2023-03-10 17:17 UTC, yosefe approved these changes

2023-03-10 17:42 UTC, merged