UCT/IB/RC: only use DEVx to connect RCQP created by DEVx
openucx/ucx pull request #9246
Opened 2023-07-26 13:40 UTC by changchengx

## What
Only use DEVx to connect RC/QP created by DEVx 

## Why ?
If ```rcqp``` isn't enumerated in ```UCX_IB_MLX5_DEVX_OBJECTS``` environment variable, it uses dv API to create the ```rcqp```. Under this case, it should use ```dv&verbs``` API to operate the ```rcqp``` instead of using DEVx.

## How ?
check ```md->flags``` against ```UCT_IB_MLX5_MD_FLAG_DEVX_RC_QP``` instead of ```UCT_IB_MLX5_MD_FLAG_DEVX```

2023-07-27 10:08 UTC, changchengx commented
It reports below two failed test cases in **UCX PR(Tests roce_proto_disable on worker3)**. I'll check it at weekend.
```
2023-07-27T00:13:14.2204077Z [  FAILED  ] 2 tests, listed below:
2023-07-27T00:13:14.2204426Z [  FAILED  ] ib/multi_rail_max.max_lanes/2, where GetParam() = ib/rndv_put_zcopy
2023-07-27T00:13:14.2204828Z [  FAILED  ] ib/multi_rail_max.max_lanes/6, where GetParam() = ib/send_nbr
```

2023-07-29 08:23 UTC, changchengx commented
It needs to trigger re-run the above failed test cases after analysis.

2023-07-30 09:13 UTC, yosefe approved these changes

2023-07-30 09:14 UTC, yosefe requested changes
Actually, why is this needed?
We can create QP by verbs and connect with DevX

2023-07-30 10:26 UTC, changchengx commented
> Actually, why is this needed? We can create QP by verbs and connect with DevX
>
1. I agree with that ```We can create QP by verbs and connect with DevX```.
2. When some object types are not listed in ```UCX_IB_MLX5_DEVX_OBJECTS```, it means that it won't use DEVX to create the object. It maybe better to use the corresponding API to modify the created object to check how it's implemented with using verbs or direct verbs.

2023-07-30 10:32 UTC, yosefe commented
> > Actually, why is this needed? We can create QP by verbs and connect with DevX
> 
> 1. I agree with that `We can create QP by verbs and connect with DevX`.
> 2. When some object types are not listed in `UCX_IB_MLX5_DEVX_OBJECTS`, it means that it won't use DEVX to create the object. It maybe better to use the corresponding API to modify the created object to check how it's implemented with using verbs or direct verbs.

It's intentional (and supported by fw/driver) to allow creating qp by verbs and modifying using devx.

2023-07-30 10:42 UTC, changchengx commented
> It's intentional (and supported by fw/driver) to allow creating qp by verbs and modifying using devx.
>
I agree with this. Let's suppose one scenario:
1. Build UCX with DEVx
2. The running environment also supports DEVx
3. ```rcqp``` isn't listed in ```UCX_IB_MLX5_DEVX_OBJECTS```. Then, dv API is used to create rcqp. In current code, it use DEVx to modify QP into RTS.
4. However, if the user wants to use rdma-core dv API to check some qp info, without this PR, the user has to look for the method to do it with DEVx. With this PR, the user can use standard rdma-core dv API to check it directly.
5. One example: if the user want to check rc qp affinity, ```mlx5dv_query_qp_lag_port``` is enough to do it without the requirement to know how to use DEVx to do it. Use ```mlxdv_query_qp_lag_port``` in ```uct_rc_iface_qp_connect``` is easy to be understood.

2023-07-30 12:31 UTC, yosefe commented
@changchengx item (4) is not clear - user code do not have access to UCX QP.
And when DevX is enabled, UCX should use DevX to query QP properties (including QP affinity) and not DV API.
This way we can also support rdma-core versions that do not have mlx5dv_query_qp_lag_port API.

2023-07-30 12:51 UTC, changchengx commented
> when DevX is enabled, UCX should use DevX to query QP properties (including QP affinity) and not DV API.
>
I agree with you now. Let me close this PR.

2023-07-30 12:51 UTC, closed without merging