GTEST/UCT: Limit MEMIC allocation to prevent out-of-memory test failures
openucx/ucx pull request #9892
Opened 2024-05-21 15:54 UTC by gleon99

## What
Cap MEMIC allocations, to reduce out-of-memory failures

## Why ?
Memory is very limited, and some might already be allocated.

2024-05-21 16:00 UTC, yosefe commented on test/gtest/uct/test_atomic_key_reg_rdma_mem_type.cc
> +        modify_config("DM_COUNT", 0);
do we create entities in uct_amo_test::init? if yes modify the config before init()

2024-05-21 16:03 UTC, gleon99 commented on test/gtest/uct/test_md.cc
> +                                       ucs_max(md_attr().max_alloc / 8, 1024));
re (1) - see line 416 below. no need to add extra checks, it's already there..

2024-05-21 18:23 UTC, gleon99 commented on test/gtest/uct/test_md.cc
> +    const auto max_alloc          = ucs_max(md_attr().max_alloc / 8, 1024);
I think line 417 prevents it. Anyway, I'll refactor a bit. Push shortly.

2024-05-21 18:36 UTC, gleon99 commented
@yosefe I made some refactoring to remove excessive ops in each iter. wdyt?

2024-05-22 07:17 UTC, yosefe commented on test/gtest/uct/test_md.cc
> +    max_size               = ucs_rounddown_pow2(max_size);
maybe do ucs_align_down_pow2(max_size, sizeof(size_t)) ?

2024-05-22 10:05 UTC, yosefe approved these changes

2024-05-22 10:08 UTC, yosefe requested changes

2024-05-22 10:08 UTC, yosefe commented on test/gtest/uct/test_atomic_key_reg_rdma_mem_type.cc
> +        modify_config("DM_COUNT", 0);
IMO it should be IB_DM_COUNT
pls validate it really works..

2024-05-23 06:45 UTC, yosefe approved these changes

2024-05-27 06:21 UTC, merged